### ISSUE TITLE
Creating tiles

### ISSUE THREAD

**Issue by hebrewd** [flathub/org.mapeditor.Tiled#4] opened 2019-01-20 15:07 UTC
It doesn't seem to work with the flatpak'd version, it does work with the native one.
It might be due to permissions.

I am running Fedora 29.

**Comment by TingPing** [comment] 2019-01-20 16:34
Could you be more specific?

**Comment by hebrewd** [comment] 2019-01-20 19:09
Yes, sorry if I am too vague, it's just that the error message that return is empty by itself.
But, I am able to save to the file system from the flatpak, when I select a tileset to generate tiles from however, it does fail, alas, loading a file from the filesystem fails.

I am attaching an image to hopefully provide more details.  
  

![screenshot from 2019-01-20 21-08-31](https://user-images.githubusercontent.com/12696810/51443840-998a7a80-1cf7-11e9-8c83-5bd25eee3118.png)  
  
![screenshot from 2019-01-20 21-08-43](https://user-images.githubusercontent.com/12696810/51443843-a3ac7900-1cf7-11e9-9aa0-b353393976f9.png)
  
  
When I am installing the package that is provided by the fedora repos however, everything works just fine, same file, saving to the same location.

**Comment by TingPing** [comment] 2019-01-20 19:14
I do see the same extension warning but saving actually works fine here. Also on Fedora 29 (GNOME).

**Comment by hebrewd** [comment] 2019-01-20 19:16
When you generate tiles? or just create a map? because creating a map does work for me as well.

**Comment by TingPing** [comment] 2019-01-20 19:17
I just made a map, sorry I'm not too familiar with the application.

The fact saving maps works is extra confusing then.

**Comment by hebrewd** [comment] 2019-01-20 19:22
True, I did played with it for a bit to try and figure it out, tried various locations as well.
You can try to verify that the issue is not just on me, you just need to provide a image file of sort to create a tile set.

**Comment by TingPing** [comment] 2019-01-20 19:36
I can reproduce it and I updated the version to the latest and it still happens. So I don't know what would be the problem off-hand. I don't think its a permission issue.

**Comment by Kekun** [comment] 2020-04-20 19:38
I hit that bug today with the current version from Flathub: I can't save tilesets.

I can open existing tilesets, but I can't save one, whether it's a new one I am creating or one I opened.

**Comment by bjorn** [comment] 2021-09-22 08:21
I've just installed the Tiled Flatpak on elementary OS 6 and could no longer reproduce this issue. Could it be that is was fixed?

The org.mapeditor.Tiled Flatpak version is 2019.07.05 for some reason, but Tiled reports that it is version 1.7.2 (released on 10.08.2021).

**Comment by bjorn** [comment] 2022-05-16 12:57
Closing this since the problem appears to be gone now.

**Closed as completed by bjorn** 2022-05-16 12:57 UTC
